'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/handler.js', 'hello');

describe('hello', () => {
  before((done) => {
    done();
  });

  it('hello should have a non-empty response', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });

  it('hello should have a valid reponse', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).equals(200)
    expect(JSON.parse(response.body).message).equals("Go Serverless v1.0! Your function executed successfully!")
  });
  
});
